### ISSUE TITLE
Auto completion fails with "Exception: Prelude.last: empty list"

### ISSUE THREAD

**Issue by larskuhtz** [fpco/ide-backend#274]
```haskell
λ f <- getAutocompletion s
λ f m ""
*** Exception: Prelude.last: empty list
```

**Comment by snoyberg** [comment]
Can you please provide:

* A more complete reproducing test case
* Your GHC version and OS

**Comment by larskuhtz** [comment]
I think the issue is caused by this code: https://github.com/fpco/ide-backend/blob/33214f5c69fef90f8c6bb9ecc948f8425e67abf7/ide-backend/IdeSession/Query.hs#L300:

```haskell
getAutocompletion :: Query (ModuleName -> String -> [IdInfo])
getAutocompletion = computedQuery $ \Computed{..} ->
    autocomplete computedCache computedAutoMap
  where
    autocomplete :: Private.ExplicitSharingCache
                 -> Strict (Map ModuleName) (Strict Trie (Strict [] (XShared IdInfo)))
                 -> ModuleName -> String
                 -> [IdInfo]
    autocomplete cache mapOfTries modName name =
        let name' = BSSC.pack name
            n     = last (BSSC.split '.' name')
```

I think the function `autocomplete cache mapOfTries` is returned by `getAutocompletion`. If it is given `""` for the `name` parameter the error occurs.

My GHC version is 7.10.1 and the OS is Mac OS X. But I don't think that this makes a difference here.

**Comment by snoyberg** [comment]
Here's a reproducing test case:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import IdeSession

main :: IO ()
main = do
    session <- initSession defaultSessionInitParams defaultSessionConfig
    updateSession session
        (updateSourceFile "Main.hs" "main = return ()")
        print
    ac <- getAutocompletion session
    print $ ac "Main" "put"
    print $ ac "Main" ""
```

You're correct, that's the source of the problem. The question is what the best solution is. I can think of three options:

1. Change the API to return a `Maybe` or `Either` value to indicate invalid input. I strongly dislike this option, but wanted to put it out there.
2. Return an empty list when the input is empty
3. Return all possible identifiers for empty input

Even though it's certainly overkill, I'm leaning towards (3) as the right answer, since it gives a (possibly useful to someone) value for currently invalid input. Thoughts?

**Comment by chrisdone** [comment]
I'd lean towards (2) or (3) too, but given that you can achieve (2) as a user of the API by simply not calling it, (3) seems to provide more value.

**Comment by snoyberg** [comment]
Pushed. @larskuhtz Can you confirm before we close and release?

**Comment by larskuhtz** [comment]
I can't reproduce the issue any more on master.

Thanks @snoyberg for the quick fix!
